postgresql:
    container_name: postgresql
    image: secret06/jenkins:0.1
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - /etc/postgresql:/etc/postgresql:rw
	- /var/log/postgresql:/var/log/postgresql:rw
	- /var/lib/postgresql:/var/lib/postgresql:rw
