version: '2'
services:
   localservice_data:
     container_name: localservice_data
     image: secret06/localservice:latest
     restart: always
     tty: true

   mysql:
     container_name: mysql
     image: secret06/mysql:v1.1.2
     volumes:
       - db_data:/var/lib/mysql
     command: mysqld --innodb_buffer_pool_size=8G  --sql-mode=""
     ports:
       - "3306:3306"
     restart: always

   nginx:
    container_name: nginx
    image: secret06/nginx:tabsquare-1.0
    restart: always
    ports:
        - "7000:7000"
    volumes_from:
        - localservice_data:rw
    links:
        - fpm-7
        - mysql

   fpm-7:
     container_name: fpm-7
     restart: always
     image: secret06/php:7.1.1
     volumes_from:
        - localservice_data:rw

   monitoring:
     container_name: monitoring
     restart: always
     image: djenriquez/sherpa
     command: --allow
     volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
     ports:
        - "2375:4550"

   #integerationserver:
     #container_name: integerationserver
     #image: integerationserver:v1.0.0
     #tty: true
     #volumes_from:
       # - localservice_data:rw
     #links:
        #- mysql
   integerationservice:
        container_name: integerationservice
        image: mono:latest
        volumes:
          - "./integeration:/var/integerationservice:rw"
        volumes_from:
           - localservice_data:rw
        tty: true
        command: mono /var/integerationservice/IntegrationServer.exe
        links:
          - mysql
volumes:
    db_data: