version: '2'
services:
   localservice_data:
     container_name: localservice_data
     image: secret06/localservice:latest
     restart: always
     tty: true

   mysql:
     container_name: mysql
     image: secret06/mysql:v1.1.0
     ports:
       - "3306:3306"
     restart: always

   nginx:
    container_name: nginx
    image: secret06/nginx:tabsquare-1.0
    restart: always
    ports:
        - "7000:7000"
    volumes_from:
        - localservice_data:rw
    links:
        - fpm-7
        - mysql

   fpm-7:
     container_name: fpm-7
     restart: always
     image: secret06/php:7.1.1
     volumes_from:
        - localservice_data:rw

volumes:
    db_data: