version: '2'
services:
  nginx:
    container_name: nginx
    image: secret06/nginx
    restart: always
    ports:
        - "8000:8000"
        - "9000:9000"
        - "7000:7000"
        - "6000:6000"
    volumes:
        - /Users/agungjulisman/Documents/app:/var/www/html:rw
        - /Users/agungjulisman/Documents/conf.d:/etc/nginx/conf.d:rw
#        - /Users/agungjulisman/Documents/tes/nginx.conf:/etc/nginx/nginx.conf:rw
    links:
        - fpm

  fpm:
     container_name: fpm
     restart: always
     image: php:5.6.2
     volumes:
        - /Users/agungjulisman/Documents/app:/var/www/html:z

