nginx:
    container_name: nginx
    image: secret06/nginx
    restart: always
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/www/html:/var/www/html:rw
        - /mnt/docker/nginx/conf.d:/etc/nginx/conf.d:rw
    links:
        - hhvm

hhvm:
  container_name: hhvm
  image: hhvm/hhvm
  command: hhvm --mode server --config /etc/hhvm/hhvm.ini
  volumes:
      - /var/www/html:/var/www/html:rw

