nginx:
    container_name: nginx
    image: secret06/nginx
    restart: always
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/www/html:/var/www/html
        - /mnt/docker/nginx/conf.d:/etc/nginx/conf.d