version: '2'

services:
   db:
     container_name: mysql
     image: mysql:5.7
     ports:
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql
       - /Users/agungjulisman/Documents/docker/mysql/db_data/:/var/db_data:rw
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: changeit
       MYSQL_DATABASE: changeit
       MYSQL_USER: changeit
       MYSQL_PASSWORD: changeit

volumes:
    db_data:
