ralali_nginx:
  image: nginx2:2.0
  ports:
    - "8000:8000"
  volumes:
    - .:/var/www/php/website
  links:
    - ralali_hhvm

ralali_hhvm:
  image: hhvm2:0.1
  command: hhvm --mode server --config /etc/hhvm/hhvm.ini
  volumes:
     - .:/var/www/php/website


