ralali_data5:
  image: website:0.1

ralali_web_nginx19:
  image: nginx2:2.0
  ports:
    - "8000:80"
  volumes_from:
    - ralali_data5
  links:
    - ralali_hhvm

ralali_hhvm:
  image: hhvm2:0.1
  command: hhvm --mode server --config /etc/hhvm/hhvm.ini


